### ISSUE TITLE
Not generating files in Ubuntu 16.04

### ISSUE THREAD

**Issue by adamconkey** [kuka-isir/lwr_project_creator#1]
Has this utility been tested on Ubuntu 16.04? When I run the command suggested in the documentation:

    lwr_create_pkg my_controller -C MyController

I see the following output:

    Using default class name : MyController
    Project to be generated
    
    
    
    Successfully created files in /home/adam/ros_ws/src. Please adjust the values in package.xml.

But it doesn't actually create any files in the specified directory. I know I used this tool successfully in Ubuntu 14.04 in the past, so I'm wondering if the Ubuntu version is at issue or if there is something else wrong with my system.

**Comment by ahoarau** [comment]
Thanks for pointing that out. It should be fixed with  c7156c2

**Comment by adamconkey** [comment]
That fixed it! It's generating the files now. Thanks for the quick turnaround.
