### ISSUE TITLE
InvalidPackage error during catkin build

### ISSUE THREAD

**Issue by adamconkey** [kuka-isir/lwr_project_creator#2]
The recent [fix](https://github.com/kuka-isir/lwr_project_creator/commit/c7156c2d10a7444db5dcd82bc2ab2e48003d6b0a) for the [file generation issue](https://github.com/kuka-isir/lwr_project_creator/issues/1) may have broken something. I am getting the following error in the catkin build step when doing a clean install of the RTT LWR packages:

```
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/geneus/geneus_main.py", line 137, in genmain
    pkg_map = get_pkg_map()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/geneus/geneus_main.py", line 56, in get_pkg_map
    pkgs = packages.find_packages(ws)
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/packages.py", line 86, in find_packages
    packages = find_packages_allowing_duplicates(basepath, exclude_paths=exclude_paths, exclude_subspaces=exclude_subspaces, warnings=warnings)
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/packages.py", line 146, in find_packages_allowing_duplicates
    xml, filename=filename, warnings=warnings)
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/package.py", line 594, in parse_package_string
    pkg.validate(warnings=warnings)
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/package.py", line 268, in validate
    raise InvalidPackage('\n'.join(errors))
InvalidPackage: Package name "@PROJECT_NAME@" does not follow naming conventions
ERROR:  Package name "@PROJECT_NAME@" does not follow naming conventions
CMakeFiles/lwr_fri_generate_messages_eus.dir/build.make:116: recipe for target '/home/adam/ros_ws/devel/.private/lwr_fri/share/roseus/ros/lwr_fri/manifest.l' failed
make[2]: *** [/home/adam/ros_ws/devel/.private/lwr_fri/share/roseus/ros/lwr_fri/manifest.l] Error 3
make[1]: *** [CMakeFiles/lwr_fri_generate_messages_eus.dir/all] Error 2
CMakeFiles/Makefile2:1741: recipe for target 'CMakeFiles/lwr_fri_generate_messages_eus.dir/all' failed
```

When I delete the `lwr_project_creator` package and do catkin clean and build, the error goes away.

**Comment by ahoarau** [comment]
Actually this is excellent , because Travis is complaining about this but I could not reproduce it . I'll fix it shortly.

**Comment by ahoarau** [comment]
On travis it complains about krl_msgs also. Did you run ``catkin clean -y`` and build again ?
I need some clues on how to reproduce this

**Comment by adamconkey** [comment]
Initially I had noticed it when building a workspace that extends the rtt_lwr workspace, and in that one I did catkin clean but I didn't use any flags. But then I tried removing all of the rtt workspaces (orocos_toolchain, rtt_ros_integration, and rtt_lwr) and reinstalled them from scratch as described on your documentation. And then I was getting the error even just building the rtt_lwr workspace.

**Comment by ahoarau** [comment]
And if you remove this package (lwr_project_creator) it works (clean first) ?

**Comment by adamconkey** [comment]
Correct, to get my code to build I just deleted lwr_project_creator, catkin clean, catkin build, and it worked.

**Comment by ahoarau** [comment]
Ok it should be ok now. I thought I created the CATKIN_IGNORE in bee8c282742aea13a66196075f1cc21b517b7b47, but apprently .gitignore ignored it :-1: I'm waiting for travis to confirm, but could you also check if it works ?

**Comment by ahoarau** [comment]
Apparently fixed ! https://travis-ci.org/kuka-isir/rtt_lwr/builds/299637284
